import pandas as pd                                                                                                                                                                                                             
import json                                                                                                                                                                                                                     
from pathlib import Path                                                                                                                                                                                                        
import shutil                                                                                                                                                                                                                   
                                                                                                                                                                                                                                
base = Path('/home/ubuntu/surgery-automation/dataset/local/pi05-pp')                                                                                                                                                            
data_dir = base / 'data'                                                                                                                                                                                                        
meta = base / 'meta'                                                                                                                                                                                                            
                                                                                                                                                                                                                                
# Read all parquet files                                                                                                                                                                                                        
chunks = sorted(data_dir.glob('chunk-*/*.parquet'))                                                                                                                                                                             
print(f'Reading {len(chunks)} files...')                                                                                                                                                                                        
all_dfs = [pd.read_parquet(p) for p in chunks]                                                                                                                                                                                  
df = pd.concat(all_dfs).sort_values(['episode_index', 'frame_index']).reset_index(drop=True)                                                                                                                                    
print(f'Total frames: {len(df)}')                                                                                                                                                                                               
                                                                                                                                                                                                                                
# Back up old data                                                                                                                                                                                                              
backup = base / 'data_backup'                                                                                                                                                                                                   
if not backup.exists():                                                                                                                                                                                                         
    shutil.move(str(data_dir), str(backup))                                                                                                                                                                                     
    print('Backed up old data dir')                                                                                                                                                                                             
                                                                                                                                                                                                                                
# Write one file per episode in v2.1 format                                                                                                                                                                                     
chunks_size = 1000                                                                                                                                                                                                              
for ep_idx in sorted(df['episode_index'].unique()):                                                                                                                                                                             
    ep_chunk = ep_idx // chunks_size                                                                                                                                                                                            
    chunk_dir = data_dir / f'chunk-{ep_chunk:03d}'                                                                                                                                                                              
    chunk_dir.mkdir(parents=True, exist_ok=True)                                                                                                                                                                                
    ep_df = df[df['episode_index'] == ep_idx]                                                                                                                                                                                   
    out_path = chunk_dir / f'episode_{ep_idx:06d}.parquet'                                                                                                                                                                      
    ep_df.to_parquet(out_path)                                                                                                                                                                                                  
                                                                                                                                                                                                                                
print(f'Wrote {len(df["episode_index"].unique())} episode files')                                                                                                                                                               
                                                                                                                                                                                                                                
# Update data_path in info.json                                                                                                                                                                                                 
with open(meta / 'info.json') as f:                                                                                                                                                                                             
    info = json.load(f)                                                                                                                                                                                                         
info['data_path'] = 'data/chunk-{episode_chunk:03d}/episode_{episode_index:06d}.parquet'                                                                                                                                        
with open(meta / 'info.json', 'w') as f:                                                                                                                                                                                        
    json.dump(info, f, indent=2)                                                                                                                                                                                                
print('Updated info.json data_path')                                                                                                                                                                                            