import pandas as pd                                                                                                                                                                                                             
import json                                                                                                                                                                                                                     
from pathlib import Path                                                                                                                                                                                                        
                                                                                                                                                                                                                                
meta = Path('/home/ubuntu/surgery-automation/dataset/local/pi05-pp/meta')                                                                                                                                                       
data_dir = Path('/home/ubuntu/surgery-automation/dataset/local/pi05-pp/data')                                                                                                                                                   
                                                                                                                                                                                                                                
# Read all parquet files to get per-episode info                                                                                                                                                                                
chunks = sorted(data_dir.glob('chunk-*/*.parquet'))                                                                                                                                                                             
print(f'Found {len(chunks)} parquet files')                                                                                                                                                                                     
                                                                                                                                                                                                                                
all_dfs = []                                                                                                                                                                                                                    
for p in chunks:                                                                                                                                                                                                                
    all_dfs.append(pd.read_parquet(p, columns=['episode_index', 'frame_index', 'task_index']))                                                                                                                                  
                                                                                                                                                                                                                                
df = pd.concat(all_dfs)                                                                                                                                                                                                         
episodes = []                                                                                                                                                                                                                   
for ep_idx in sorted(df['episode_index'].unique()):                                                                                                                                                                             
    ep_data = df[df['episode_index'] == ep_idx]                                                                                                                                                                                 
    length = len(ep_data)                                                                                                                                                                                                       
    task_idx = int(ep_data['task_index'].iloc[0])                                                                                                                                                                               
    episodes.append({                                                                                                                                                                                                           
        'episode_index': int(ep_idx),                                                                                                                                                                                           
        'length': length,                                                                                                                                                                                                       
        'task_index': task_idx,                                                                                                                                                                                                 
    })                                                                                                                                                                                                                          
                                                                                                                                                                                                                                
with open(meta / 'episodes.jsonl', 'w') as f:                                                                                                                                                                                   
    for ep in episodes:                                                                                                                                                                                                         
        f.write(json.dumps(ep) + '\n')                                                                                                                                                                                          
                                                                                                                                                                                                                                
print(f'Created episodes.jsonl with {len(episodes)} episodes')                                                                                                                                                                  
print('First 3:', episodes[:3])  