import datasets                                                                                                                                                                                                                 
from pathlib import Path                                                                                                                                                                                                        
                                                                                                                                                                                                                                
base = Path('/home/ubuntu/surgery-automation/dataset/local/pi05-pp')                                                                                                                                                            
data_dir = base / 'data'                                                                                                                                                                                                        
                                                                                                                                                                                                                                
image_cols = [                                                                                                                                                                                                                  
    'observation.images.WRIST_LEFT',                                                                                                                                                                                            
    'observation.images.WRIST_RIGHT',                                                                                                                                                                                           
    'observation.images.TOP_VIEW',                                                                                                                                                                                              
    'observation.images.BACK_VIEW',                                                                                                                                                                                             
]                                                                                                                                                                                                                               
                                                                                                                                                                                                                                
for parquet_file in sorted(data_dir.glob('chunk-*/*.parquet')):                                                                                                                                                                 
    print(f'Fixing {parquet_file.name}...')                                                                                                                                                                                     
    ds = datasets.Dataset.from_parquet(str(parquet_file))                                                                                                                                                                       
    for col in image_cols:                                                                                                                                                                                                      
        ds = ds.cast_column(col, datasets.Image())                                                                                                                                                                              
    ds.to_parquet(str(parquet_file))                                                                                                                                                                                            
                                                                                                                                                                                                                                
print('Done') 